/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes.Interfaz;

/**
 *
 * @author USER
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1queue = new javax.swing.JLabel();
        l2queue = new javax.swing.JLabel();
        l3queue = new javax.swing.JLabel();
        lrqueue = new javax.swing.JLabel();
        b1queue = new javax.swing.JLabel();
        b2queue = new javax.swing.JLabel();
        b3queue = new javax.swing.JLabel();
        brqueue = new javax.swing.JLabel();
        lnumcars = new javax.swing.JLabel();
        bnumcars = new javax.swing.JLabel();
        aistatus = new javax.swing.JLabel();
        adminstatus = new javax.swing.JLabel();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        l1queue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1queue.setText("N/A");

        l2queue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2queue.setText("N/A");

        l3queue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3queue.setText("N/A");

        lrqueue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lrqueue.setText("N/A");

        b1queue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1queue.setText("N/A");

        b2queue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2queue.setText("N/A");

        b3queue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b3queue.setText("N/A");

        brqueue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brqueue.setText("N/A");

        lnumcars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnumcars.setText("N/A");

        bnumcars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bnumcars.setText("N/A");

        aistatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aistatus.setText("N/A");

        adminstatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminstatus.setText("N/A");

        message.setText("N/A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lrqueue, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l3queue, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2queue, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1queue, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnumcars, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aistatus, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brqueue, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3queue, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2queue, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1queue, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnumcars, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(message)
                .addContainerGap(371, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(message)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aistatus)
                    .addComponent(adminstatus))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnumcars)
                    .addComponent(bnumcars))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b1queue)
                        .addGap(18, 18, 18)
                        .addComponent(b2queue)
                        .addGap(18, 18, 18)
                        .addComponent(b3queue)
                        .addGap(18, 18, 18)
                        .addComponent(brqueue))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l1queue)
                        .addGap(18, 18, 18)
                        .addComponent(l2queue)
                        .addGap(18, 18, 18)
                        .addComponent(l3queue)
                        .addGap(18, 18, 18)
                        .addComponent(lrqueue)))
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel adminstatus;
    public javax.swing.JLabel aistatus;
    public javax.swing.JLabel b1queue;
    public javax.swing.JLabel b2queue;
    public javax.swing.JLabel b3queue;
    public javax.swing.JLabel bnumcars;
    public javax.swing.JLabel brqueue;
    public javax.swing.JLabel l1queue;
    public javax.swing.JLabel l2queue;
    public javax.swing.JLabel l3queue;
    public javax.swing.JLabel lnumcars;
    public javax.swing.JLabel lrqueue;
    public javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
